import 'package:final__quiz_app/answer_button.dart';
import 'package:final__quiz_app/data/questions.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

class QuestionScreen extends StatefulWidget {
  const QuestionScreen({super.key, required this.onChooseAnswer});

  final void Function(String clickedAnswer) onChooseAnswer;
  // final void Function(String clickedAnswer) onChooseAnswer;--> this is function present in widget class i need to acess it into State class
  //insnstance variable.... widget.onChooseAnswer--> this is how we access instance variable of widget class into state class
  @override
  State<QuestionScreen> createState() {
    return _QuestionScreenState();
  }
}

class _QuestionScreenState extends State<QuestionScreen> {
  var currentQuestionIdx = 0;

  void answeringQuestion(String clickedAnswer) {
    widget.onChooseAnswer(
        clickedAnswer); //the instance of the widget that the current build function is creating
    setState(() {
      currentQuestionIdx++;
    });
  }

  @override
  Widget build(context) {
    var currentQuestion = questions[currentQuestionIdx];

    return SizedBox(
      width: double
          .infinity, //use as much width as u can..be as much wide as possible
      child: Container(
        margin: const EdgeInsets.all(40),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Text(
              currentQuestion.questionText,
              textAlign: TextAlign.center,
              style: GoogleFonts.lato(
                textStyle: const TextStyle(
                  color: Color.fromARGB(255, 4, 54, 83),
                  fontSize: 24,
                  fontWeight: FontWeight.bold,
                ),
              ),
            ),
            const SizedBox(height: 30),
            // .map is used in converting Strings to Widgets when given in form of lists
            //... these 3 dots spreads this list generated by map into a couple of individual values
            // ...currentQuestion.answers.map((item) {
            ...currentQuestion.getShuffledAnswers().map((item) {
              return AnswerButton(
                item,
                onTap: () {
                  answeringQuestion(item);
                },
              ); //converting list of String TO AnswerButton widget
            }), //map does not change the original list instead it returns a new list full of new objects
            // AnswerButton(currentQuestion.answers[0], onTap: () {}),
            // AnswerButton(currentQuestion.answers[1], onTap: () {}),
            // AnswerButton(currentQuestion.answers[2], onTap: () {}),
            // AnswerButton(currentQuestion.answers[3], onTap: () {}),
          ],
        ),
      ),
    );
  }
}
