import 'package:final__quiz_app/answer_button.dart';
import 'package:final__quiz_app/data/questions.dart';
import 'package:flutter/material.dart';

class QuestionScreen extends StatefulWidget {
  const QuestionScreen({super.key});

  @override
  State<QuestionScreen> createState() {
    return _QuestionScreenState();
  }
}

class _QuestionScreenState extends State<QuestionScreen> {
  @override
  Widget build(context) {
    var currentQuestion = questions[0];

    return SizedBox(
      width: double
          .infinity, //use as much width as u can..be as much wide as possible
      child: Container(
        margin: const EdgeInsets.all(40),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Text(
              currentQuestion.questionText,
              textAlign: TextAlign.center,
              style: const TextStyle(
                color: Color.fromARGB(255, 10, 76, 115),
                fontSize: 15,
                fontWeight: FontWeight.bold,
              ),
            ),
            const SizedBox(height: 30),
            // .map is used in converting Strings to Widgets when given in form of lists
            //... these 3 dots spreads this list generated by map into a couple of individual values
            ...currentQuestion.answers.map((item) {
              return AnswerButton(
                item,
                onTap: () {},
              ); //converting list of String TO AnswerButton widget
            }), //map does not change the original list instead it returns a new list full of new objects
            // AnswerButton(currentQuestion.answers[0], onTap: () {}),
            // AnswerButton(currentQuestion.answers[1], onTap: () {}),
            // AnswerButton(currentQuestion.answers[2], onTap: () {}),
            // AnswerButton(currentQuestion.answers[3], onTap: () {}),
          ],
        ),
      ),
    );
  }
}
